name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          # If you are using user generated values like the title of an issue, 
          # it's strongly recommended that you first store them in an environment variable 
          # before using those values anywhere in the commands you are executing.
          TITLE: ${{ github.event.issue.title }}
        # run: |
        #   issue_title="${{ github.event.issue.title }}"
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi